### ISSUE TITLE
Checking for exit(0)

### ISSUE THREAD

**Issue by ghost** [dorothysyu/part2#18]
0 typically represents a successful exit in a program. This should be change to a non-zero value

**Comment by ghost** [comment]
Nevermind, it accepts all exit codes. Do you know why when I use exit(-1) or exit(0) it says the following?
    Result: died but not with expected exit code:
            Terminated by signal 6 (core dumped)
When I uncomment the ASSERT_DEATH the test passes

**Comment by dorothysyu** [comment]
Is this only failing for tests with assert deaths? Perhaps I should separate out those tests. I can open a new branch that will assert death in separate test cases

**Comment by dorothysyu** [comment]
I just pushed a new branch, you can try out that test file if you want and lmk what happens

**Comment by ghost** [comment]
The tests still failed. I also did the statement below but it still failed.
TEST(W1, testBoolAtFail) { CS4500_ASSERT_DEATH(exit(0)); }

**Comment by dorothysyu** [comment]
https://github.com/dorothysyu/part2/issues/19: i pushed a change that'll comment out the death cases
